AppAllinum/urls.py
from django.conf.urls import url
from django.urls import include

urlpatterns = [
    #    path('admin/', admin.site.urls),
    url(r'^', include('core.urls'))
]

core/urls.py
from django.conf.urls import url

from core.views import *

urlpatterns = [
    url(r'^login/$', efetuar_login, name='login'),
    url(r'^logout/$', efetuar_logout, name='logout'),
    url(r'^usuario_cadastro/$', usuario_cadastro, name='usuario_cadastro'),
    url(r'^usuario_delete/$', usuario_delete, name='usuario_delete'),
    url(r'^usuario_editar/(?P<pk>[0-9]+)', usuario_editar, name='usuario_editar'),
    url(r'^usuario_lista/$', usuario_lista, name='usuario_lista'),
    url(r'^usuario_configuracao/$', usuario_configuracao, name='usuario_configuracao'),
    url(r'^projeto_cadastro/$', projeto_cadastro, name='projeto_cadastro'),
    url(r'^projeto_delete/$', projeto_delete, name='projeto_delete'),
    url(r'^projeto_editar/(?P<pk>[0-9]+)', projeto_editar, name='projeto_editar'),
    url(r'^projeto_lista/$', projeto_lista, name='projeto_lista'),
    url(r'^tarefa_cadastro/(?P<pk>[0-9]+)', tarefa_cadastro, name='tarefa_cadastro'),
    url(r'^tarefa_editar/(?P<pk>[0-9]+)', tarefa_editar, name='tarefa_editar'),
    url(r'^tarefa_delete/$', tarefa_delete, name='tarefa_delete'),
    url(r'^visao_tarefa/$', tarefa_visao, name='visao_tarefa'),
    url(r'^visao_projeto/(?P<pk>[0-9]+)', projeto_visao, name='visao_projeto'),
    url(r'^visao_projeto_tarefa/(?P<pk>[0-9]+)', tarefas_do_usuario_projeto, name='visao_projeto_tarefa'),
    url(r'^visao_requisito/(?P<pk>[0-9]+)', visao_requisitos, name='visao_requisito'),
    url(r'^requisito_cadastro/$', requisito_cadastro, name='requisito_cadastro'),
    url(r'^requisito_delete/$', requisito_delete, name='requisito_delete'),
    url(r'^redefinicao_senha_admin/$', redefinicao_senha_admin, name='redefinicao_senha_admin'),
    url(r'^redefinicao_senha/$', redefinicao_senha, name='redefinicao_senha'),
    url(r'^esqueceu_senha/$', esqueceu_senha, name='esqueceu_senha'),
    url(r'^concluir_tarefa/(?P<pk>[0-9]+)', concluir_tarefa, name='concluir_tarefa')
]

core/models/profile.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matricula = models.TextField(max_length=20, unique=True)
    tema = models.TextField(max_length=1)
    fontes_grandes = models.BooleanField(default=False)


# noinspection PyUnusedLocal
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# noinspection PyUnusedLocal
@receiver(post_save, sender=User)
def alter_user_profile(sender, instance, **kwargs):
    instance.profile.save()

core/models/projeto.py
from django.contrib.auth.models import User
from django.db import models
from .membro import Membro


class Projeto(models.Model):
    titulo = models.TextField(max_length=100, null=False)
    descricao = models.TextField(max_length=400, null=False)
    lider = models.ForeignKey(User, on_delete=models.CASCADE)
    membros = models.ManyToManyField(Membro)
    ult_alt = models.TextField(max_length=100, null=True)
    data_ult_alt = models.DateField(null=True)

core/models/tarefa.py
from django.db import models
from .membro import Membro
from .projeto import Projeto
from .categoria import Categoria


class Tarefa(models.Model):
    titulo = models.CharField(max_length=100, null=False)
    resp = models.ForeignKey(Membro, on_delete=models.CASCADE)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    prioridade = models.CharField(max_length=15, null=True)
    data_limite = models.DateField(null=True)
    concluido = models.BooleanField(default=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

templates/baseLogin.html
<html lang="pt-br">
    {% load static %}
	<head>
		<meta charset="utf-8"/>
		<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">

	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

	    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

		<title> {% block title %} {% endblock %} </title>

	</head>
	<body style = 'background: {% block backgroundColor %} {% endblock %};'>
		<div class="row">

			<div class="col s4"> </div>

			<div class="col s4" style = 'background: {% block quadroBlock %} {% endblock %}; height: 80%; margin-top: 5%; border-radius: 20px;'>

				<div class="row">

		    		<div class="input-field col s3"></div>
		    		<div class="input-field col s6">
		    			<img src="{% static 'usuarios/logos/Logo_H_C.png' %}" style="width: 100%";>
		    		</div>
		    		<div class="input-field col s3"></div>

				</div>

                <div class="row">
                    {% block conteudo %} {% endblock %}
                </div>

			</div>

			<div class="col s4"> </div>
		</div>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                crossorigin="anonymous"> </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"> </script>

        <script>

            {% if messages %}
                {% for message in messages %}
                    $(document).ready(function() {
                        Materialize.toast('{{ message }}', 4000)
                    });
                {% endfor %}
            {% endif %}

          </script>
	</body>
</html>

templates/baseTemplate.html
<html lang="pt-br">
    {% load static %}
	<head>
		<meta charset="utf-8"/>
		<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">

		<!-- Compiled and minified CSS -->
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <style>
            p, div, label, button, a{
                font-family: 'Work Sans', sans-serif;
            }

            h1, h2, h3, h4, h5, th{
                font-family: 'Lato', sans-serif;
            }

        </style>


		<title> {% block title %} {% endblock %} </title>

	</head>
	<body style = 'background:  {% if request.user.profile.tema == 'C' %}
                                    #64FFDA
                                {% endif %}

                                {% if request.user.profile.tema == 'N' %}
                                    #01579B
                                {% endif %};'>
		<nav>
		    <div class="nav-wrapper {% if request.user.profile.tema == 'C' %}
                                        light-blue darken-2
                                    {% endif %}

                                    {% if request.user.profile.tema == 'N' %}
                                        blue-grey darken-4
                                    {% endif %}">
		      	<a href="{% url 'projeto_lista' %}" style="margin-left: 40px; color:#FFFFFF;">
                    {% if request.user.profile.tema == 'C' %}
                        <img src = "{% static 'usuarios/logos/Logo_C.png' %}" style = "height: 40px; margin-top: 1%;"/>
                    {% endif %}
                    {% if request.user.profile.tema == 'N' %}
                        <img src = "{% static 'usuarios/logos/Logo_N.png' %}" style = "height: 40px; margin-top: 1%;"/>
                    {% endif %}
                </a>

		      	<ul id="nav-mobile" class="right">

                    <li style="margin-right: 10px;"> Olá, {{ request.user.first_name}} </li>

			      	<li {% if menu == "projetos" %}class="active" {% endif %}><a href=" {% url 'projeto_lista' %} " style="height: 100%; width: 120px;">
			      		<img src = "{% static 'usuarios/icons/projetos.png' %}" style = "width: 40%; margin-left: 30%; margin-top: 20%;">
			      	</a></li>

			      	<li {% if menu == "tarefas" %}class="active" {% endif %}><a href="{% url 'visao_tarefa' %}" style="height: 100%; width: 120px;">
			      		<img src = "{% static 'usuarios/icons/tarefas.png' %}" style = "width: 40%; margin-left: 30%; margin-top: 20%;">
			      	</a></li>

			        <li {% if menu == "configuracoes" %}class="active" {% endif %}><a href=" {% url 'usuario_configuracao' %} " style="height: 100%; width: 120px;">
			      		<img src = "{% static 'usuarios/icons/configuracoes.png' %}" style = "width: 40%; margin-left: 30%; margin-top: 20%;">
			      	</a></li>

			        <li><a href="{% url 'logout' %}" style="height: 100%; width: 120px;">
			        	<img src = "{% static 'usuarios/icons/sair.png' %}" style = "width: 40%; margin-left: 30%; margin-top: 20%;">
			        </a></li>

		      	</ul>
		    </div>
	  	</nav>

	  	<div class = row>
	  		<div class = "col s12" style = "height: 25px; background:   {% if request.user.profile.tema == 'C' %}
                                                                            #01579B
                                                                        {% endif %}
                                                                        {% if request.user.profile.tema == 'N' %}
                                                                            #0288D1
                                                                        {% endif %};
                    color: #FFFFFF; text-align: center;"> {% block titulo %} {% endblock %} </div>
	  	</div>

		<div class = 'col s12' style = "background: {% if request.user.profile.tema == 'C' %}
                                                        #FFFFFF
                                                    {% endif %}
                                                    {% if request.user.profile.tema == 'N' %}
                                                        #263238
                                                    {% endif %};
                min-height: 80%; margin: 1%; border: 5px solid #00BFA5; border-radius: 15px;">

            {% block conteudo %}
            {% endblock %}

		</div>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                crossorigin="anonymous"> </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"> </script>

        <script>

            $(document).ready(function() {
                $('select').material_select();
            });

            document.addEventListener('DOMContentLoaded', function() {
			    var elems = document.querySelectorAll('#projetos-options');
			    var instances = M.FloatingActionButton.init(elems, options);
			});

            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.collapsible');
                var instances = M.Collapsible.init(elems, options);
            });

            $(document).ready(function(){
			    $('.modal').modal();
			});

            {% if messages %}
                {% for message in messages %}
                    $(document).ready(function() {
                        Materialize.toast('{{ message }}', 4000)
                    });
                {% endfor %}
            {% endif %}

          </script>
	</body>
</html>

templates/esqueceu_senha.html
{% extends 'baseLogin.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. Esqueceu a Senha
{% endblock title %}

<!-- Cor de fundo da página -->
{% block backgroundColor %}
    #64FFDA
{% endblock backgroundColor %}

<!-- Cor do Quadro da página -->
{% block quadroBlock %}
    #FFFFFF
{% endblock quadroBlock %}

<!-- Conteúdo da Página -->
{% block conteudo %}
    <div class="row">

        <div class="col s1">  </div>

        <div class="col s10">

            <h5> Recuperar Senha </h5>
            <p> Entre em contato com algum adminstrador do sistema e solicite para que altere sua senha </p>

        </div>

        <div class="col s1">  </div>

    </div>

    <div class="row">
        <div class = "col s4"> </div>

        <div class="input-field col s4">
            <a href="{% url 'login' %}">
                <button class="btn waves-effect waves-light" style="width: 100%;">
                     Voltar
                </button>
            </a>
        </div>

        <div class = "col s4"> </div>
    </div>
{% endblock conteudo %}

templates/login.html
{% extends 'baseLogin.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. Login
{% endblock title %}

<!-- Cor de fundo da página -->
{% block backgroundColor %}
    #64FFDA
{% endblock backgroundColor %}

<!-- Cor do Quadro da página -->
{% block quadroBlock %}
    #FFFFFF
{% endblock quadroBlock %}

<!-- Conteúdo da Página -->
{% block conteudo %}
    <form class="col s12" method="post" action=".?next={{ redirect_to }}"> {% csrf_token %}

        <label for="username"> Usuário </label>
        <input placeholder="Nome de Usuário" id="username" name="username" type="text" class="validate">

        <label for="password"> Senha </label>
        <input placeholder="Password" id="password" name="password" type="password" class="validate">

        <a href="{% url 'esqueceu_senha' %}"> Esqueci a minha senha </a>

        <div class="row">
            <div class = "col s4"> </div>
                <div class="input-field col s4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Entrar <i class="material-icons right">send</i>
                    </button>
                </div>
            <div class = "col s4"> </div>
        </div>

    </form>
{% endblock conteudo %}

templates/projeto_cadastro.html
{% extends 'baseTemplate.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. Projeto
{% endblock title %}

<!-- Titulo que aparece no SubMenu da Página -->
{% block titulo %}
    Cadastro de Projeto
{% endblock titulo %}

<!-- Conteúdo da Página (Hexadecimal) -->
{% block conteudo %}
    <div class = "row" style="margin-top: 20px;">
        <div class = "col s2">	</div>

        <form class="col s8" method="POST"> {% csrf_token %}

            <div class = "row">
				<div class="col s12">
					<label for="id_titulo"> Titulo: </label>
					<input name="titulo" cols="40" rows="10" minlength="5" maxlength="100" required id="id_titulo"/>
				</div>
			</div>

			<div class = "row">
				<div class="col s12">
					<label for="id_descricao"> Descrição: </label>
				</div>
			</div>

			<div class = "row">
				<div class="col s12">
					<textarea name="descricao" cols="40" rows="10" minlength="15" maxlength="400" required id="id_descricao"></textarea>
				</div>
			</div>

            <div class = "row">
				<div class="col s12 input-field ">
					<select multiple name="membros">
                        <option value="" disabled> </option>
					  	{% for membro in membro_list %}
                            {% if membro.user.id != request.user.id and not membro.user.is_superuser %}
                            <option value="{{ membro.id }}"> {{ membro.user.username }} </option>
                            {% endif %}
                        {% endfor %}
					</select>
                <label >Membros:</label>
				</div>
			</div>

			<input type="hidden" name="lider" required id="id_lider" value="{{ request.user.pk }}">

            <div class="row">
                <div class="input-field col s2">
                    <button class="btn waves-effect waves-light blue-grey lighten-4">
                        <a href=" {% url 'projeto_lista' %}" class="black-text text-lighten-5">Cancelar</a>
                    </button>
                </div>

                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Cadastrar <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>

        </form>

        <div class = "col s2">	</div>
    </div>
{% endblock conteudo %}

templates/projeto_lista.html
{% extends 'baseTemplate.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. Projetos
{% endblock title %}

<!-- Titulo que aparece no SubMenu da Página -->
{% block titulo %}
    Projetos
{% endblock titulo %}

<!-- Conteúdo da Página (Hexadecimal) -->
{% block conteudo %}
    <div class = "row" style="margin-top: 20px;">
        <div class = "col s11" style="margin-left:20px">

            <table {% if request.user.profile.tema == 'N' %} class="light-blue-text text-lighten-5" {% endif %}>
                <thead>
                    <tr>
                        <th> Titulo </th>
                        <th> Descrição </th>
                        <th> Ult. Alteração </th>
                        <th> Líder </th>
                    </tr>
                </thead>

                <tbody>
                {% for projeto in context %}
                    <tr>
                        <td> <a href="{% url 'visao_projeto' pk=projeto.pk %}"> {{ projeto.titulo }} </a> </td>
                        <td> {{ projeto.descricao }} </td>
                        <td> {{ projeto.ult_alt }} em {{ projeto.data_ult_alt }} </td>
                        {% if projeto.lider == request.user or user.is_superuser %}
                        <td>
                            <a href="{% url 'projeto_editar' pk=projeto.pk %}">
                                <i class="material-icons">create</i>
                            </a>
                            <a href="#modal1">
                                <i class="material-icons">delete</i>
                            </a>
                        </td>
                        {% endif %}
                        {% if projeto.lider != request.user and not user.is_superuser %}
                        <td> {{ projeto.lider }} </td>
                        {% endif %}
                    </tr>


                    <div id="modal1" class="modal">
                        <div class="modal-content">
                            <h4>Apagar Projeto</h4>
                            <p>Tem certeza que deseja excluir o projeto "{{ projeto.titulo }}"?</p>
                        </div>

                        <div class="modal-footer">
                            <div class="row">
                                <div class="col s4"></div>
                                <div class="col s4">
                                    <button href="#!" class="modal-close waves-effect waves-green btn-flat">Cancelar</button>
                                </div>
                                <div class="col s4">
                                    <form method="post" action="{% url 'projeto_delete' %}"> {% csrf_token %}
                                        <input type="hidden" name="pk" value="{{ projeto.pk }}">
                                        <button type="submit" class="waves-effect waves-green btn-flat red darken-2" style="position:relative; top:-15px; left: -20px">Deletar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div style="position: absolute; bottom:50px; right: 50px;">
          <a class="btn-floating btn-large waves-effect waves-light light-blue darken-4" href = "{% url 'projeto_cadastro' %}"><i class="material-icons">add</i></a>
    </div>

{% endblock conteudo %}

templates/tarefa_cadastro.html
{% extends 'baseTemplate.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. {{ projeto.titulo }}
{% endblock title %}

<!-- Titulo que aparece no SubMenu da Página -->
{% block titulo %}
    {{ projeto.titulo }} > Cadastro de Tarefa
{% endblock titulo %}

<!-- Conteúdo da Página (Hexadecimal) -->
{% block conteudo %}
    <div class = "row" style="margin-top: 20px;">
        <div class = "col s2">	</div>

        <form class="col s8" method="POST"> {% csrf_token %}

            <div class = "row">
				<div class="col s12">
					<label for="id_titulo"> Titulo: </label>
					<input name="titulo" cols="40" rows="10" minlength="5" maxlength="100" required id="id_titulo"/>
				</div>
			</div>

            <div class = "row">
				<div class="col s12">
					<label for="id_resp"> Responsável: </label>
                    <select id="id_resp" name = "resp" required>
                        <option value = "" disabled selected> Escolha uma opção </option>
                        {% for membro in membro_list %}
                            <option value = "{{ membro.pk }}"> {{ membro.user.username}} </option>
                        {% endfor %}
                    </select>
				</div>
			</div>

            <input type="hidden" name="projeto" required id="id_projeto" value="{{ projeto.pk }}">

            <div class = "row">
				<div class="col s12">
					<label for="id_categoria"> Categoria: </label>
                    <select id="id_categoria" name = "categoria" required>
                        <option value = "" disabled selected> Escolha uma opção </option>
                        {% for categoria in categoria_list %}
                            <option value = "{{ categoria.pk }}"> {{ categoria.nome }} </option>
                        {% endfor %}
                    </select>
				</div>
			</div>

            <div class = "row">
				<div class="col s6">
					<label for="id_prioridade"> Prioridade: </label>
                    <select name = "prioridade" id="id_prioridade" required>
                        <option class="white-text" value = "" disabled selected> Escolha uma opção </option>
                        <option value = "baixa"> Baixa </option>
                        <option value = "media"> Média </option>
                        <option value = "alta"> Alta </option>
                    </select>
				</div>
                <div class="col s6">
					<label for="id_data_limite"> Data: </label>
                    <input type="date" id="id_data_limite" name="data_limite">
				</div>
			</div>

            <div class="row">
                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light blue-grey lighten-4">
                        <a href=" {% url 'visao_projeto' pk=projeto.pk %}" class="black-text text-lighten-5">Cancelar</a>
                    </button>
                </div>

                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Cadastrar
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock conteudo %}

templates/tarefa_editar.html
{% extends 'baseTemplate.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. {{ projeto.titulo }}
{% endblock title %}

<!-- Titulo que aparece no SubMenu da Página -->
{% block titulo %}
    {{ projeto.titulo }} > Cadastro de Tarefa
{% endblock titulo %}

<!-- Conteúdo da Página (Hexadecimal) -->
{% block conteudo %}
    <div class = "row" style="margin-top: 20px;">
        <div class = "col s2">	</div>

        <form class="col s8" method="POST"> {% csrf_token %}

            <div class = "row">
				<div class="col s12">
					<label for="id_titulo"> Titulo: </label>
					<input name="titulo" cols="40" rows="10" minlength="5" maxlength="100" required id="id_titulo" value="{{ tarefa.titulo }}"/>
				</div>
			</div>

            <div class = "row">
				<div class="col s12">
					<label for="id_resp"> Responsável: </label>
                    <select id="id_resp" name = "resp" required>
                        <option value = "" disabled selected> Escolha uma opção </option>
                        {% for membro in membro_list %}
                            <option value = "{{ membro.pk }}" {% if membro.pk == tarefa.resp.id %} selected {% endif %}> {{ membro.user.username}} </option>
                        {% endfor %}
                    </select>
				</div>
			</div>

            <input type="hidden" name="projeto" required id="id_projeto" value="{{ projeto.pk }}">

            <div class = "row">
				<div class="col s12">
					<label for="id_categoria"> Categoria: </label>
                    <select id="id_categoria" name = "categoria" required>
                        <option value = "" disabled selected> Escolha uma opção </option>
                        {% for categoria in categoria_list %}
                            <option value = "{{ categoria.pk }}" {% if categoria.pk == tarefa.categoria.id %} selected {% endif %}> {{ categoria.nome }} </option>
                        {% endfor %}
                    </select>
				</div>
			</div>

            <div class = "row">
				<div class="col s6">
					<label for="id_prioridade"> Prioridade: </label>
                    <select name = "prioridade" id="id_prioridade" required>
                        <option value = "" disabled> Escolha uma opção </option>
                        <option value = "baixa" {% if "baixa" == tarefa.prioridade %} selected {% endif %}> Baixa </option>
                        <option value = "media" {% if "media" == tarefa.prioridade %} selected {% endif %}> Média </option>
                        <option value = "alta" {% if "alta" == tarefa.prioridade %} selected {% endif %}> Alta </option>
                    </select>
				</div>
                <div class="col s6">
					<label for="id_data_limite"> Data: </label>
                    <input type="date" id="id_data_limite" name="data_limite" value="{{data_limite_tratada}}">
				</div>
			</div>

            <div class="row">
                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light blue-grey lighten-4">
                        <a href=" {% url 'visao_projeto' pk=projeto.pk %}" class="black-text text-lighten-5">Cancelar</a>
                    </button>
                </div>

                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light red lighten-2">
                        <a href="#modal1" class="black-text text-lighten-5">Excluir</a>
                    </button>
                </div>

                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div id="modal1" class="modal {% if request.user.profile.tema == 'N' %} blue-grey darken-4 blue-grey-text text-lighten-3 {% endif %}">
        <div class="modal-content">
            <h4> Apagar Tarefa </h4>
            <p>Tem certeza que deseja excluir a Tarefa "{{ tarefa.titulo }}"?</p>
        </div>

        <div class="modal-footer {% if request.user.profile.tema == 'N' %} blue-grey darken-4 {% endif %}">
            <div class="row">
                <div class="col s4"></div>
                <div class="col s4">
                    <button href="#!" class="modal-close waves-effect waves-green btn-flat {% if request.user.profile.tema == 'N' %} blue-grey-text text-lighten-3 {% endif %}">Cancelar</button>
                </div>
                <div class="col s4">
                    <form method="post" action="{% url 'tarefa_delete' %}"> {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ tarefa.pk }}">
                        <input type="hidden" name="projeto" value="{{ projeto.pk }}">
                        <button type="submit" class="waves-effect waves-green btn-flat red darken-2 white-text" style="position:relative; left: -20px">Deletar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock conteudo %}

templates/usuario_cadastro.html
{% extends 'baseTemplate.html' %}

<!-- Title da Página -->
{% block title %}
    Allinum .:. Cadastro
{% endblock title %}

<!-- Titulo que aparece no SubMenu da Página -->
{% block titulo %}
    Cadastro de Usuário
{% endblock titulo %}

<!-- Conteúdo da Página (Hexadecimal) -->
{% block conteudo %}
    <div class = "row" style="margin-top: 20px;">
        <div class = "col s2">	</div>

        <form class="col s8" method="POST"> {% csrf_token %}

            <div class = "row">
                <div class="col s6">
                    <label for="nome"> Nome: </label>
                    <input id="nome" name="nome" minlength="5" maxlength="30" type="text" class="validate" required>
                </div>
                <div class="col s6">
                    <label for="sobrenome"> Sobrenome: </label>
                    <input id="sobrenome" name="sobrenome"  minlength="5" maxlength="30" type="text" class="validate">
                </div>
            </div>

            <div class = "row">
                <div class="col s6">
                    <label for="usuario"> Usuário: </label>
                    <input id="usuario" name="usuario"  minlength="5" maxlength="20" type="text" class="validate" required>
                </div>
            </div>

            <div class = "row">
                <div class="col s6">
                    <label for="id_matricula"> Matrícula </label>
                    <input id="id_matricula" name="matricula"  minlength="8" maxlength="8" type="text" class="validate" required>
                </div>
            </div>

            <div class = "row">
                <div class="col s6">
                    <label for="senha"> Senha </label>
                    <input id="senha" name="senha" type="password" minlength="8" class="validate" required>
                </div>

                <div class="col s6">
                    <label for="confirma_senha"> Confirma Senha </label>
                    <input id="confirma_senha" name="confirma_senha" minlength="8" type="password" class="validate" required>
                </div>
            </div>

            <div class = "row">
                <div class="col s6">
                    <label> Tipo de usuário </label>
                    <select name = "tipo_usuario" required>
                        <option value = "" disabled selected> Escolha uma opção </option>
                        <option value = "administrador"> Adminstrador </option>
                        <option value = "usuario"> Usuário </option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light blue-grey lighten-4">
                        <a href=" {% url 'usuario_lista' %}" class="black-text text-lighten-5">Cancelar</a>
                    </button>
                </div>

                <div class="input-field col s3">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Cadastrar <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>

        </form>

        <div class = "col s2">	</div>
    </div>
{% endblock conteudo %}